services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
      PORT: 3000
    depends_on:
      - db
  worker:
    build: .
    command: npm run worker
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
    depends_on:
      - db

volumes:
  pgdata:
